config1: "./configs/config_09.yaml"
config2: "./configs/config_06.yaml"
exp_dir: "./exp/"
exp_name: 'exp-11'
mode: 'fusion_embeds'

model: 'LinearSVC'
model_params:
    penalty: ['l1', 'l2']
    C: [0.001, 0.01, 0.1, 1.0]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   refit: 'f1_score'
   verbose: 2
   n_jobs: -1

