config1: "./configs/config_02.yaml"
config2: "./configs/config_08.yaml"
mode: 'fusion_probs'

model: 'RandomForestClassifier'
model_params:
    n_estimators: ['range', 100, 1000, 50]
    criterion: ['gini', 'entropy']
    max_depth: ['range', 3, 10]
    bootstrap: [True, False]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "RandomizedSearchCV"
cv_params:
   refit: 'f1_score'
   n_iter: 30
   verbose: 1
   n_jobs: -1

