config1: "./configs/config_02.yaml"
config2: "./configs/config_08.yaml"
mode: 'fusion_embeds'

model: 'LogisticRegression'
model_params:
    solver: ['lbfgs', 'liblinear']
    penalty: ['l1', 'l2']
    C: [0.001, 0.01, 0.1, 1.0]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   refit: 'f1_score'
   verbose: 1
   n_jobs: -1

