config1: "./configs/cnn/cnn-roof_type-efficientnetb0-RGB_DOM.yaml"
config2: "./configs/cnn/cnn-roof_type-inceptionv3-LIDAR_DOM.yaml"
mode: 'fusion_embeds'

model: 'LogisticRegression'
model_params:
    solver: ['lbfgs', 'liblinear']
    penalty: ['l1', 'l2']
    C: [0.001, 0.01, 0.1, 1.0]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   refit: 'f1_score'
   verbose: 2
   n_jobs: -1
   cv: 5
