rasters_dir: './data/rasters/'
csv_dir: './data/csv/'
exp_dir: './exp/'

version: 'version_02'
attribute: 'roof_material'
exp_name: 'exp_11'
mode: 'RGB'
batch_size: 32
n_workers: 4
n_epochs: 30

model: "resnet50"
resampler: "RandomOverSampler"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 0.1
lr: 0.00001
img_size: 224
patience: 7
dropout: 0.5
momentum: 
gamma: 
step_size: 