attribute: 'roof_material'
data: 'RGB_DOM'
batch_size: 32
n_workers: 4
n_epochs: 60

model: "resnet50"
resampler: "RandomOverSampler"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 0.1
lr: 0.00001
img_size: 224
patience: 7
dropout: 0.5
momentum: 
gamma: 
step_size: 