aoi: 'DOM'
version: 'version-02'
rasters_dir: './data/rasters/'
vectors_dir: './data/vectors/'
csv_dir: './data/csv/'
attributes: ['roof_type', 'roof_material']

bldgs_file: 'building_footprints_annotated_DOM.gpkg'
rgb_source_file: 'ortho/ortho_DOM.tif'
ndsm_source_file: 'lidar/ndsm_DOM.tif'