data_dir: './data/rasters/Tiles/ortho/'
csv_dir: './data/csv/'
attribute: 'roof_material'
exp_name: 'exp-03'
batch_size: 32
n_workers: 4
n_epochs: 2

model: "inceptionv3"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
lr: 0.001
img_size: 299
momentum: 
gamma: 
step_size: 
patience: 7
dropout: 