data_dir: './data/rasters/Tiles/ndsm/'
csv_dir: './data/csv/'
attribute: 'roof_material'
exp_name: 'exp-06'
mode: 'GRAYSCALE'
batch_size: 32
n_workers: 4
n_epochs: 30

model: "inceptionv3"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
lr: 0.00001
img_size: 299
momentum: 
gamma: 
step_size: 
patience: 7
dropout: 