data_dir: './data/rasters/Tiles/ortho/'
csv_dir: './data/csv/'
attribute: 'roof_type'
exp_name: 'exp-02'
batch_size: 16
n_workers: 4
n_epochs: 60

model: "resnet50"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
lr: 0.0001
momentum: None
gamma: None
step_size: None
patience: 10
dropout: 0.50