data_dir: './data/rasters/Tiles/ortho/'
csv_dir: './data/csv/'
attribute: 'roof_type'
exp_name: 'exp-02'
batch_size: 32
n_workers: 4
n_epochs: 50

model: "resnet50"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
lr: 0.00001
momentum: None
gamma: None
step_size: None
patience: 7
dropout: 0.2